blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
                  path(r'reg/', views.register, name='reg'),
                  path(r'login/', views.login_view, name='login'),
                  path(r'index/', views.index, name='index'),
              ]

my_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_blog import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path(r'', include(('blog.urls', 'blog'), namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from tinymce.models import HTMLField


# 用户模型
class User(AbstractUser):
    head = models.ImageField(upload_to='head/%Y/%m', default='head/user.png', max_length=200, verbose_name='用户头像')
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='qq号码')

    class Meta:
        ordering = ['-id']
        verbose_name_plural = verbose_name = "用户"

    def __unicode__(self):
        return self.username

    def __str__(self):
        return self.username


# 标签模型
class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name="标签名称")

    class Meta:
        verbose_name_plural = verbose_name = "标签"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


# 分类模型
class Catagory(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name="分类名称")
    index = models.IntegerField(default=999, unique=True, verbose_name="分类的排序")

    class Meta:
        verbose_name_plural = verbose_name = '分类'
        ordering = ('index', 'name')

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


# 文章模型
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name="文章标题")
    desc = models.CharField(max_length=50, verbose_name='文章描述')
    content = HTMLField(verbose_name="文章内容")
    click_count = models.IntegerField(default=0, verbose_name="点击次数")
    is_recommend = models.BooleanField(default=False, verbose_name="是否推荐")
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    user = models.ForeignKey(User, verbose_name="用户", on_delete=models.CASCADE)
    category = models.ForeignKey(Catagory, blank=True, null=True, verbose_name="分类", on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, verbose_name="标签")

    class Meta:
        verbose_name_plural = verbose_name = '文章'
        ordering = ['-date_publish']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


# 评论模型
class Comment(models.Model):
    content = models.TextField(verbose_name="评论内容")
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    user = models.ForeignKey(User, blank=True, null=True, verbose_name="用户", on_delete=models.CASCADE)
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name="文章", on_delete=models.CASCADE)
    pid = models.ForeignKey("self", blank=True, null=True, verbose_name="父级评论", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = verbose_name = "评论"
        ordering = ['-date_publish']

    def __unicode__(self):
        return str(self.id)

    def __str__(self):
        return str(self.id)


# 友情链接
class Links(models.Model):
    title = models.CharField(max_length=50, verbose_name="标题")
    description = models.CharField(max_length=50, verbose_name="友情链接描述")
    callback_url = models.URLField(null=True, blank=True, verbose_name="回调url")
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    index = models.IntegerField(default=900, verbose_name="排列顺序（从小到大）")

    class Meta:
        verbose_name_plural = verbose_name = "友情链接"
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


# 广告
class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name="广告标题")
    description = models.CharField(max_length=50, verbose_name="广告描述")
    image_url = models.ImageField(upload_to='ad/%Y/%m', verbose_name="图片路径")
    callback_url = models.URLField(null=True, blank=True, verbose_name="回调url")
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    index = models.IntegerField(default=900, unique=True, verbose_name="排列顺序（从小到大）")

    class Meta:
        verbose_name_plural = verbose_name = "广告"
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class BlogPic(models.Model):
    filename = models.CharField(max_length=200, blank=True, null=True)
    img = models.ImageField(upload_to='upload/%Y/%m')

templates/blog_login.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE HTML>
<html lang="zxx">
<head>
    <title>{{ SITE_NAME }}</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8"/>
    <meta name="keywords"
          content="Triple Forms Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements"/>
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        };
    </script>
    <!-- Meta tag Keywords -->

    <!-- css files -->
    <link rel="stylesheet" href="{% static 'log_css/style.css' %}" type="text/css" media="all"/>
    <!-- Style-CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Font-Awesome-Icons-CSS -->
    <!-- //css files -->

    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext"
          rel="stylesheet">
    <!-- //web-fonts -->
</head>

<body>
<div class="main-bg">
    <!-- title -->
    <h1>{{ SITE_NAME }}</h1>
    <!-- //title -->
    <div class="sub-main-w3">
        <div class="image-style">

        </div>
        <!-- vertical tabs -->
        <div class="vertical-tab">
            <div id="section1" class="section-w3ls">
                <input type="radio" name="sections" id="option1" checked>
                <article>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <h3 class="legend">Login Here</h3>
                        <div class="input">
                            <span class="fa fa-user" aria-hidden="true"></span>
                            {{userform.username }}
                        </div>
                        <div class="input">
                            <span class="fa fa-key" aria-hidden="true"></span>
                            {{userform.password}}
                        </div>
                        <button type="submit" class="btn submit">Login</button>
                        <a href="#" class="bottom-text-w3ls">Forgot Password?</a>
                    </form>
                </article>
            </div>
        </div>
        <!-- //vertical tabs -->
        <div class="clear"></div>
    </div>
</div>

</body>

</html>

templates/blog_register.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE HTML>
<html lang="zxx">
<head>
    <title>{{ SITE_NAME }}</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8"/>
    <meta name="keywords"
          content="Triple Forms Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements"/>
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Meta tag Keywords -->

    <!-- css files -->
    <link rel="stylesheet" href="{% static 'log_css/style.css' %}" type="text/css" media="all"/>
    <!-- Style-CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Font-Awesome-Icons-CSS -->
    <!-- //css files -->

    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext"
          rel="stylesheet">
    <!-- //web-fonts -->
</head>

<body>
<div class="main-bg">
    <!-- title -->
    <h1>{{ SITE_NAME }}</h1>
    <!-- //title -->
    <div class="sub-main-w3">
        <div class="image-style">

        </div>
        <!-- vertical tabs -->
        <div class="vertical-tab">
            <div id="section2" class="section-w3ls">
                <input type="radio" name="sections" id="option2" checked>
{#                <label for="option2" class="icon-left-w3pvt"><span class="fa fa-pencil-square"#}
{#                                                                   aria-hidden="true"></span>Register</label>#}
                <article>
{#                    <div>{{ error }}</div>#}
                    <form action="{% url 'blog:reg' %}" method="POST">
                        {% csrf_token %}
                        <h3 class="legend">Register Here</h3>
                        <div class="input">
                            <span class="fa fa-user" aria-hidden="true"></span>
                            {{userform.username }}
                        </div>
                        <div class="input">
                            <span class="fa fa-envelope-o" aria-hidden="true"></span>
                            {{userform.email }}
                        </div>
                        <div class="input">
                            <span class="fa fa-key" aria-hidden="true"></span>
                            {{userform.password }}
                        </div>
                        <div class="input">
                            <span class="fa fa-key" aria-hidden="true"></span>
                            {{userform.conf_password}}
                        </div>
                        <button type="submit" class="btn submit">Register</button>
                    </form>
                </article>
            </div>
        </div>
        <!-- //vertical tabs -->
        <div class="clear"></div>
    </div>
</div>

</body>

</html>

templates/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block menu %}
    {% include 'base/menu.html' %}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
{% endblock %}

{#轮播图#}
{% block swiper %}
    <div class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper" style="margin-top: 60px">
            {% for ad in ad_list %}
                <div class="swiper-slide" align="center">
                    <a href="#"><img class="slide_img" src="{{ MEDIA_URL }}{{ ad.image_url }}" alt=""></a>
                </div>
            {% endfor %}
        </div>
        <!-- 如果需要分页器 -->
        <div class="swiper-pagination"></div>
    </div>
{% endblock %}
{#正文#}
{% block content %}
    <div class="topnews" style="width: 90%">
        <h2>最新文章</h2>
        <div style="background-color: orange;width: 90%;height: 20px;"></div>
        <div style="; height: 40px;"></div>

        {% for article in page_article %}
            <div class="blogs" style="margin-left: 0px">
                <ul>
                    <h3><a href="#"
                           style="font-weight: bolder;line-height: 2px;color: black;font-size: 30px">{{ article.title }}</a>
                    </h3>
                    <p style="color: lightskyblue;width: 10%;overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">{{ article.desc }}</p>
                    <p class="author"><span>作者:{{ article.user }}</span>&nbsp;{% for tag in article.tag.all %}
                        <span>标签:{{ tag }}</span>
                    {% endfor %}
                        &nbsp;<span>发布日期：{{ article.date_publish|date:'Y-m-d' }}</span>
                        &nbsp;<span style="float: right;margin-right: 15%">浏览(<a href="#">{{ article.click_count }}</a>)</span>
                        &nbsp;<span style="float: right;margin-right: 5%">评论(<a
                                href="#">{{ article.comment_set.all.count }}</a>)</span>
                    </p>
                </ul>
                <div style="; height: 20px;"></div>
                <div style="; width: 90%;height: 5px;background-color: lightgrey"></div>
            </div>
        {% endfor %}

        <div style="width: 90%; height: 50px;"></div>
        {#    分页#}
        <div style="margin-left: 39%">
            <a href="{% url 'blog:index' %}?page=1">首页</a>
            {% if page_article.has_previous %}
                <a href="{% url 'blog:index' %}?page={{ page_article.previous_page_number }}">上一页</a>
            {% else %}
                <a href="javascript:alert('已经是首页了！')">上一页</a>
            {% endif %}

            {% if page_article.has_next %}
                <a href="{% url 'blog:index' %}?page={{ page_article.next_page_number }}">下一页</a>
            {% else %}
                <a href="javascript:alert('已经是最后一页了！')">下一页</a>
            {% endif %}
            <a href="{% url 'blog:index' %}?page={{ paginator.num_pages }}">末页</a>
        </div>

        <div style="width: 90%; height: 100px;"></div>
        <p style="margin-left: 43%">学无止境</p>
        <div style="width: 90%; height: 2px;background-color: orange;margin-bottom: 100px"></div>

    </div>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.js' %}"></script>
{% endblock %}

templates/index_bak.html
{% extends 'base/base.html' %}

{% block menu %}
    {% include 'base/menu.html' %}
{% endblock %}

{% block content %}
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa-file-text-o"></i> Form elements</h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
                    <li><i class="icon_document_alt"></i>Forms</li>
                    <li><i class="fa fa-file-text-o"></i>Form elements</li>
                </ol>
            </div>
        </div>
        <!--      正文部分     -->
        <section class="wrapper">
            <!--                表单开始-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Form Elements
                        </header>
                        <div class="panel-body">
                            <form class="form-horizontal " method="get">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Default</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </section>

                </div>
            </div>
            <!--                表单结束-->

            <!--                表格开始-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Advanced Table
                        </header>

                        <table class="table table-striped table-advance table-hover">
                            <tbody>
                            <tr>
                                <th><i class="icon_profile"></i> Full Name</th>
                                <th><i class="icon_calendar"></i> Date</th>
                                <th><i class="icon_mail_alt"></i> Email</th>
                                <th><i class="icon_pin_alt"></i> City</th>
                                <th><i class="icon_mobile"></i> Mobile</th>
                                <th><i class="icon_cogs"></i> Action</th>
                            </tr>
                            <tr>
                                <td>Angeline Mcclain</td>
                                <td>2004-07-06</td>
                                <td>dale@chief.info</td>
                                <td>Rosser</td>
                                <td>176-026-5992</td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-primary" href="#"><i class="icon_plus_alt2"></i></a>
                                        <a class="btn btn-success" href="#"><i class="icon_check_alt2"></i></a>
                                        <a class="btn btn-danger" href="#"><i class="icon_close_alt2"></i></a>
                                    </div>
                                </td>
                            </tr>

                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
            <!--                表格结束-->
        </section>
    </section>
{% endblock %}

{% block js %}
    <script>

        //knob
        $(function () {
            $(".knob").knob({
                'draw': function () {
                    $(this.i).val(this.cv + '%')
                }
            })
        });

        //carousel
        $(document).ready(function () {
            $("#owl-slider").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

        /* ---------- Map ---------- */
        $(function () {
            $('#map').vectorMap({
                map: 'world_mill_en',
                series: {
                    regions: [{
                        values: gdpData,
                        scale: ['#000', '#000'],
                        normalizeFunction: 'polynomial'
                    }]
                },
                backgroundColor: '#eef3f7',
                onLabelShow: function (e, el, code) {
                    el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
                }
            });
        });


    </script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
{% include 'base/meta.html' %}


    <title>{{ SITE_NAME }}</title>

    <!-- Bootstrap CSS -->
{% include 'base/css.html' %}


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
{% include 'base/js.html' %}
    <![endif]-->
</head>

  <body class="login-img3-body">

    <div class="container">

      <form class="login-form" method="post">
        <div class="login-wrap">
            <p class="login-img"><i class="icon_lock_alt"></i></p>
            <div class="input-group">
              <span class="input-group-addon"><i class="icon_profile"></i></span>
              <input type="text" class="form-control" placeholder="Username" autofocus>
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="icon_key_alt"></i></span>
                <input type="password" class="form-control" placeholder="Password">
            </div>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right"> <a href="#"> Forgot Password?</a></span>
            </label>
            <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
            <button class="btn btn-info btn-lg btn-block" type="submit">Signup</button>
        </div>
      </form>

    </div>


  </body>
</html>

templates/reg_login.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE HTML>
<html lang="zxx">
<head>
    <title>{{ SITE_NAME }}</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8"/>
    <meta name="keywords"
          content="Triple Forms Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements"/>
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Meta tag Keywords -->

    <!-- css files -->
    <link rel="stylesheet" href="{% static 'log_css/style.css' %}" type="text/css" media="all"/>
    <!-- Style-CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Font-Awesome-Icons-CSS -->
    <!-- //css files -->

    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext"
          rel="stylesheet">
    <!-- //web-fonts -->
</head>

<body>
<div class="main-bg">
    <!-- title -->
    <h1>{{ SITE_NAME }}</h1>
    <!-- //title -->
    <div class="sub-main-w3">
        <div class="image-style">

        </div>
        <!-- vertical tabs -->
        <div class="vertical-tab">
            <div id="section1" class="section-w3ls">
                <input type="radio" name="sections" id="option1" checked>
                <label for="option1" class="icon-left-w3pvt"><span class="fa fa-user-circle" aria-hidden="true"></span><a
                        href="/blog/us/log/">Login</a></label>
                <article>
                    <form action="/blog/us/log/" method="post">
                        <h3 class="legend">Login Here</h3>
                        <div class="input">
                            <span class="fa fa-envelope-o" aria-hidden="true"></span>
                            {{ userform.email }}
                        </div>
                        <div class="input">
                            <span class="fa fa-key" aria-hidden="true"></span>
                            {{userform.password}}
                        </div>
                        <button type="submit" class="btn submit">Login</button>
                        <a href="#" class="bottom-text-w3ls">Forgot Password?</a>
                    </form>
                </article>
            </div>
            <div id="section2" class="section-w3ls">
                <input type="radio" name="sections" id="option2" checked>
                <article>
                    <form action="#" method="post">
                        <h3 class="legend">Register Here</h3>
                        <div class="input">
                            <span class="fa fa-user-o" aria-hidden="true"></span>
                            {{userform.username }}
                        </div>
                        <div class="input">
                            <span class="fa fa-envelope-o" aria-hidden="true"></span>
                            {{userform.email }}
                        </div>
                        <div class="input">
                            <span class="fa fa-key" aria-hidden="true"></span>
                            <input type="password" placeholder="Password" name="regpwd" required/>
                        </div>
                        <div class="input">
                            <span class="fa fa-key" aria-hidden="true"></span>
                            {{userform.conf_password}}
                        </div>
                        <button type="submit" class="btn submit">Register</button>
                    </form>
                </article>
            </div>
            <div id="section3" class="section-w3ls">
                <input type="radio" name="sections" id="option3">
                <label for="option3" class="icon-left-w3pvt"><span class="fa fa-lock" aria-hidden="true"></span>Forgot
                    Password?</label>
                <article>
                    <form action="#" method="post">
                        <h3 class="legend last">Reset Password</h3>
                        <p class="para-style">Enter your email address below and we'll send you an email with
                            instructions.</p>
                        <p class="para-style-2"><strong>Need Help?</strong> Learn more about how to <a href="#">retrieve
                            an existing
                            account.</a></p>
                        <div class="input">
                            <span class="fa fa-envelope-o" aria-hidden="true"></span>
                            <input type="email" placeholder="Email" name="email" required/>
                        </div>
                        <button type="submit" class="btn submit last-btn">Reset</button>
                    </form>
                </article>
            </div>
        </div>
        <!-- //vertical tabs -->
        <div class="clear"></div>
    </div>
    <!-- copyright -->
    <div class="copyright">
        <h2>&copy; 2019 Triple Forms. All rights reserved | Design by
            <a href="http://w3layouts.com" target="_blank">W3layouts</a>
        </h2>
    </div>
    <!-- //copyright -->
</div>

</body>

</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="path/to/swiper.min.css">
</head>
<body>
<div class="swiper-container" style="
    width: 600px;
    height: 300px;">
    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
    </div>
    <!-- 如果需要分页器 -->
    <div class="swiper-pagination"></div>

    <!-- 如果需要导航按钮 -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- 如果需要滚动条 -->
    <div class="swiper-scrollbar"></div>
</div>
<script src="path/to/swiper.min.js"></script>
</body>
</html>